name: 'Build AVADO Package'
description: 'Builds the AVADO package with GitHub actions'
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.15.0
    - run: node dist/index.js
      shell: bash
    